version: 2
jobs:
  build:
    branches:
      only:
        - master
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.6.2-node-browsers
        environment:
          PG_HOST: localhost
          PG_USER: postgres
          RAILS_ENV: test
          RACK_ENV: test
      # The following example uses the official postgres 9.6 image, you may also use circleci/postgres:9.6 
      # which includes a few enhancements and modifications. It is possible to use either image.
      - image: postgres:9.6-jessie
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: secret_friend_test
          DATABASE_URL: "postgres://ubuntu@localhost:5432/secret_friend_test"
    steps:
      - checkout
      - run:
          name: Install Ruby Dependencies
          command: bundle install
      - run: 
          name: Set up DB
          command: |
            bundle exec rails db:create db:schema:load --trace
            bundle exec rails db:migrate        